CREATE TABLE IF NOT EXISTS login_buckets(key TEXT PRIMARY KEY,started REAL NOT NULL,attempts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS feedback(id TEXT PRIMARY KEY,actor TEXT NOT NULL,report_id TEXT,event TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT NOT NULL,sent_at TEXT,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT);
CREATE TABLE IF NOT EXISTS telegram_recipients(actor TEXT PRIMARY KEY REFERENCES users(id),chat_id TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS commitment_terms(commitment_id TEXT PRIMARY KEY REFERENCES commitments(id),eta TEXT,expires_at TEXT,source TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS claim_resolutions(id TEXT PRIMARY KEY,claim_id TEXT REFERENCES claims(id),report_id TEXT REFERENCES assessments(id),actor TEXT NOT NULL,resolution TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS report_links(id TEXT PRIMARY KEY,source_report TEXT REFERENCES assessments(id),target_report TEXT REFERENCES assessments(id),actor TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS immutable_link_update BEFORE UPDATE ON report_links BEGIN SELECT RAISE(ABORT,'report resolution history is immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_link_delete BEFORE DELETE ON report_links BEGIN SELECT RAISE(ABORT,'report resolution history is immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_resolution_update BEFORE UPDATE ON claim_resolutions BEGIN SELECT RAISE(ABORT,'resolutions are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_resolution_delete BEFORE DELETE ON claim_resolutions BEGIN SELECT RAISE(ABORT,'resolutions are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_evidence_update BEFORE UPDATE ON evidence BEGIN SELECT RAISE(ABORT,'evidence is immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_evidence_delete BEFORE DELETE ON evidence BEGIN SELECT RAISE(ABORT,'evidence is immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_outcome_update BEFORE UPDATE ON outcomes BEGIN SELECT RAISE(ABORT,'outcomes are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_outcome_delete BEFORE DELETE ON outcomes BEGIN SELECT RAISE(ABORT,'outcomes are immutable'); END;
CREATE UNIQUE INDEX IF NOT EXISTS claims_lineage_unique ON claims(report_id,source_cell);
CREATE TRIGGER IF NOT EXISTS immutable_priority_update BEFORE UPDATE ON priority_snapshots BEGIN SELECT RAISE(ABORT,'priority snapshots are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_priority_delete BEFORE DELETE ON priority_snapshots BEGIN SELECT RAISE(ABORT,'priority snapshots are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_requirement_update BEFORE UPDATE ON requirements BEGIN SELECT RAISE(ABORT,'requirements are observations'); END;
CREATE TRIGGER IF NOT EXISTS immutable_requirement_delete BEFORE DELETE ON requirements BEGIN SELECT RAISE(ABORT,'requirements are retained'); END;
CREATE TRIGGER IF NOT EXISTS immutable_feedback_content BEFORE UPDATE OF actor,report_id,event,message,created_at ON feedback BEGIN SELECT RAISE(ABORT,'feedback content is immutable'); END;
PRAGMA user_version=2;
